export interface FlashcardItem {
  front: string;
  back: string;
  romaji: string;
  exampleSentence?: string;
  audioSrc?: string;
}

export type FlashcardSetCollection = {
  [key: string]: FlashcardItem[];
};

export const flashcardSets: FlashcardSetCollection = {
    'essential-phrases-greetings': [
        { front: "はい", back: "yes", romaji: "hai" },
        { front: "いいえ", back: "no", romaji: "iie" },
        { front: "ええ", back: "yes (less formal)", romaji: "ee" },
        { front: "おはようございます", back: "good morning (polite)", romaji: "ohayou gozaimasu" },
        { front: "こんにちは", back: "hello, good afternoon", romaji: "konnichiwa" },
        { front: "こんばんは", back: "good evening", romaji: "konbanwa" },
        { front: "さようなら", back: "goodbye (long term)", romaji: "sayounara" },
        { front: "じゃあ、また / またね", back: "see you later (informal)", romaji: "jaa, mata / mata ne" },
        { front: "おやすみなさい", back: "good night (polite)", romaji: "oyasuminasai" },
        { front: "ありがとう ございます", back: "thank you (polite)", romaji: "arigatou gozaimasu" },
        { front: "どうもありがとう", back: "thank you very much", romaji: "doumo arigatou" },
        { front: "どうも", back: "thanks (casual), very", romaji: "doumo" },
        { front: "どういたしまして", back: "you're welcome", romaji: "douitashimashite" },
        { front: "すみません", back: "excuse me, sorry, thank you", romaji: "sumimasen" },
        { front: "ごめんなさい", back: "I'm sorry (informal)", romaji: "gomennasai" },
        { front: "おねがいします", back: "please (request)", romaji: "onegaishimasu" },
        { front: "どうぞ", back: "please (offering), here you go", romaji: "douzo" },
        { front: "ください", back: "please give me / do", romaji: "kudasai" },
        { front: "はじめまして", back: "nice to meet you (first time)", romaji: "hajimemashite" },
        { front: "どうぞ よろしくおねがいします", back: "pleased to meet you", romaji: "douzo yoroshiku onegaishimasu" },
        { front: "いただきます", back: "expression before eating/receiving", romaji: "itadakimasu" },
        { front: "ごちそうさまでした", back: "expression after eating", romaji: "gochisousama deshita" },
        { front: "いってきます", back: "I'm going (and returning)", romaji: "ittekimasu" },
        { front: "いってらっしゃい", back: "go and come back safely", romaji: "itterasshai" },
        { front: "ただいま", back: "I'm home", romaji: "tadaima" },
        { front: "おかえりなさい", back: "welcome home", romaji: "okaerinasai" },
        { front: "もしもし", back: "hello (on phone)", romaji: "moshi moshi" },
        { front: "いらっしゃいませ", back: "welcome (shop/restaurant)", romaji: "irasshaimase" },
        { front: "しつれいします", back: "excuse me (interrupting/leaving)", romaji: "shitsurei shimasu" },
        { front: "おげんきですか", back: "how are you?", romaji: "ogenki desu ka" },
        { front: "はい、げんきです", back: "yes, I'm fine", romaji: "hai, genki desu" },
        { front: "だいじょうぶ です", back: "it's okay, I'm okay", romaji: "daijoubu desu" },
        { front: "けっこうです", back: "no thank you, that's fine", romaji: "kekkou desu" },
        { front: "わかりました", back: "I understand / understood", romaji: "wakarimashita" },
        { front: "わかりません", back: "I don't understand", romaji: "wakarimasen" },
        { front: "もう いちど おねがいします", back: "one more time, please", romaji: "mou ichido onegaishimasu" },
        { front: "ゆっくり おねがいします", back: "slowly, please", romaji: "yukkuri onegaishimasu" },
        { front: "やあ", back: "hi (casual, male)", romaji: "yaa" },
        { front: "うーん", back: "well..., hmm...", romaji: "uun" },
        { front: "ああ", back: "ah, oh", romaji: "aa" },
        { front: "そう", back: "so, that's right", romaji: "sou" },
    ],
'question-words-pronouns': [
  { front: "なに / なん", back: "what", romaji: "nani / nan" },
  { front: "だれ", back: "who", romaji: "dare" },
  { front: "どなた", back: "who (polite)", romaji: "donata" },
  { front: "いつ", back: "when", romaji: "itsu" },
  { front: "どこ", back: "where", romaji: "doko" },
  { front: "どれ", back: "which one (of 3+)", romaji: "dore" },
  { front: "どちら", back: "which one (of 2), which way (polite)", romaji: "dochira" },
  { front: "どっち", back: "which one (of 2, informal)", romaji: "dotchi" },
  { front: "どの", back: "which (+ noun)", romaji: "dono" },
  { front: "どう", back: "how", romaji: "dou" },
  { front: "どうして / なぜ", back: "why", romaji: "doushite / naze" },
  { front: "いくら", back: "how much (cost)", romaji: "ikura" },
  { front: "いくつ", back: "how many, how old", romaji: "ikutsu" },
  { front: "どんな", back: "what kind of", romaji: "donna" },
  { front: "どうやって", back: "how, by what means", romaji: "douyatte" },
  { front: "いかが", back: "how (polite)", romaji: "ikaga" },
  { front: "だれの", back: "whose", romaji: "dare no" },
  { front: "これ", back: "this (one)", romaji: "kore" },
  { front: "それ", back: "that (one, near listener)", romaji: "sore" },
  { front: "あれ", back: "that (one, over there)", romaji: "are" },
  { front: "この", back: "this (+ noun)", romaji: "kono" },
  { front: "その", back: "that (+ noun, near listener)", romaji: "sono" },
  { front: "あの", back: "that (+ noun, over there) / um...", romaji: "ano" },
  { front: "ここ", back: "here, this place", romaji: "koko" },
  { front: "そこ", back: "there, that place", romaji: "soko" },
  { front: "あそこ", back: "over there", romaji: "asoko" },
  { front: "こちら", back: "this way (polite)", romaji: "kochira" },
  { front: "そちら", back: "that way, there (polite)", romaji: "sochira" },
  { front: "あちら", back: "that way, over there (polite)", romaji: "achira" },
  { front: "わたし", back: "I", romaji: "watashi" },
  { front: "わたくし", back: "I (very formal)", romaji: "watakushi" },
  { front: "みんな", back: "everyone, all", romaji: "minna" },
  { front: "みなさん", back: "everyone (polite)", romaji: "minasan" },
  ],
  'people-family-titles': [
  { front: "ひと (人)", back: "person", romaji: "hito" },
  { front: "かた (方)", back: "person (polite)", romaji: "kata" },
  { front: "ともだち (友達)", back: "friend", romaji: "tomodachi" },
  { front: "かぞく (家族)", back: "family", romaji: "kazoku" },
  { front: "りょうしん (両親)", back: "parents", romaji: "ryoushin" },
  { front: "きょうだい (兄弟)", back: "siblings", romaji: "kyoudai" },
  { front: "こども (子供)", back: "child, children", romaji: "kodomo" },
  { front: "おとな (大人)", back: "adult", romaji: "otona" },
  { front: "おとこ (男)", back: "male, man", romaji: "otoko" },
  { front: "おとこのこ (男の子)", back: "boy", romaji: "otokonoko" },
  { front: "おんな (女)", back: "female, woman", romaji: "onna" },
  { front: "おんなのこ (女の子)", back: "girl", romaji: "onnanoko" },
  { front: "ちち (父)", back: "my father", romaji: "chichi" },
  { front: "はは (母)", back: "my mother", romaji: "haha" },
  { front: "あに (兄)", back: "my older brother", romaji: "ani" },
  { front: "あね (姉)", back: "my older sister", romaji: "ane" },
  { front: "おとうと (弟)", back: "my younger brother", romaji: "otouto" },
  { front: "いもうと (妹)", back: "my younger sister", romaji: "imouto" },
  { front: "しゅじん (主人)", back: "my husband", romaji: "shujin" },
  { front: "つま (妻)", back: "my wife", romaji: "tsuma" },
  { front: "おとうさん (お父さん)", back: "father (other's/polite)", romaji: "otousan" },
  { front: "おかあさん (お母さん)", back: "mother (other's/polite)", romaji: "okaasan" },
  { front: "おにいさん (お兄さん)", back: "older brother (other's/polite)", romaji: "oniisan" },
  { front: "おねえさん (お姉さん)", back: "older sister (other's/polite)", romaji: "oneesan" },
  { front: "おとうとさん (弟さん)", back: "younger brother (other's/polite)", romaji: "otoutosan" },
  { front: "いもうとさん (妹さん)", back: "younger sister (other's/polite)", romaji: "imoutosan" },
  { front: "ごしゅじん (ご主人)", back: "husband (other's/polite)", romaji: "goshujin" },
  { front: "おくさん (奥さん)", back: "wife (other's/polite)", romaji: "okusan" },
  { front: "おじさん", back: "uncle, middle-aged man", romaji: "ojisan" },
  { front: "おばさん", back: "aunt, middle-aged woman", romaji: "obasan" },
  { front: "おじいさん", back: "grandfather, elderly man", romaji: "ojiisan" },
  { front: "おばあさん", back: "grandmother, elderly woman", romaji: "obaasan" },
  { front: "せんせい (先生)", back: "teacher, master, doctor", romaji: "sensei" },
  { front: "がくせい (学生)", back: "student", romaji: "gakusei" },
  { front: "りゅうがくせい (留学生)", back: "international student", romaji: "ryuugakusei" },
  { front: "かいしゃいん (会社員)", back: "company employee", romaji: "kaishain" },
  { front: "いしゃ (医者)", back: "doctor (medical)", romaji: "isha" },
  { front: "かんごし (看護師)", back: "nurse", romaji: "kangoshi" },
  { front: "がいこくじん (外国人)", back: "foreigner", romaji: "gaikokujin" },
  { front: "～じん (～人)", back: "person nationality suffix", romaji: "-jin" },
  { front: "にほんじん (日本人)", back: "Japanese person", romaji: "nihonjin" },
  { front: "～さん", back: "Mr., Mrs., Miss, Ms.", romaji: "-san" },
  { front: "～ちゃん", back: "suffix for children, close friends", romaji: "-chan" },
  { front: "～くん (～君)", back: "suffix for boys, juniors", romaji: "-kun" },
  { front: "～さま (～様)", back: "Mr., Mrs. (very polite)", romaji: "-sama" },
  { front: "～たち (～達)", back: "plural suffix for people", romaji: "-tachi" },
  { front: "なまえ (名前)", back: "name", romaji: "namae" },
  ],
  'numbers-counters-money': [
  { front: "ゼロ / れい (零)", back: "zero", romaji: "zero / rei" },
  { front: "いち (一)", back: "one", romaji: "ichi" },
  { front: "に (二)", back: "two", romaji: "ni" },
  { front: "さん (三)", back: "three", romaji: "san" },
  { front: "よん / し (四)", back: "four", romaji: "yon / shi" },
  { front: "ご (五)", back: "five", romaji: "go" },
  { front: "ろく (六)", back: "six", romaji: "roku" },
  { front: "なな / しち (七)", back: "seven", romaji: "nana / shichi" },
  { front: "はち (八)", back: "eight", romaji: "hachi" },
  { front: "きゅう / く (九)", back: "nine", romaji: "kyuu / ku" },
  { front: "じゅう (十)", back: "ten", romaji: "juu" },
  { front: "ひゃく (百)", back: "hundred", romaji: "hyaku" },
  { front: "せん (千)", back: "thousand", romaji: "sen" },
  { front: "まん (万)", back: "ten thousand", romaji: "man" },
  { front: "ひとつ (一つ)", back: "one (general counter)", romaji: "hitotsu" },
  { front: "ふたつ (二つ)", back: "two (general counter)", romaji: "futatsu" },
  { front: "みっつ (三つ)", back: "three (general counter)", romaji: "mittsu" },
  { front: "よっつ (四つ)", back: "four (general counter)", romaji: "yottsu" },
  { front: "いつつ (五つ)", back: "five (general counter)", romaji: "itsutsu" },
  { front: "むっつ (六つ)", back: "six (general counter)", romaji: "muttsu" },
  { front: "ななつ (七つ)", back: "seven (general counter)", romaji: "nanatsu" },
  { front: "やっつ (八つ)", back: "eight (general counter)", romaji: "yattsu" },
  { front: "ここのつ (九つ)", back: "nine (general counter)", romaji: "kokonotsu" },
  { front: "とお (十)", back: "ten (general counter)", romaji: "too" },
  { front: "～にん (～人)", back: "counter for people", romaji: "-nin" },
  { front: "ひとり (一人)", back: "one person", romaji: "hitori" },
  { front: "ふたり (二人)", back: "two people", romaji: "futari" },
  { front: "～さい (～歳)", back: "years old", romaji: "-sai" },
  { front: "はたち (二十歳)", back: "twenty years old", romaji: "hatachi" },
  { front: "～まい (～枚)", back: "counter for flat objects", romaji: "-mai" },
  { front: "～ほん/ぽん/ぼん (～本)", back: "counter for long objects", romaji: "-hon/-pon/-bon" },
  { front: "～こ (～個)", back: "counter for small objects", romaji: "-ko" },
  { front: "～さつ (～冊)", back: "counter for bound objects", romaji: "-satsu" },
  { front: "～かい (～階)", back: "counter for floors", romaji: "-kai" },
  { front: "～かい (～回)", back: "counter for times/frequency", romaji: "-kai" },
  { front: "～ど (～度)", back: "counter for times/degrees", romaji: "-do" },
  { front: "～だい (～台)", back: "counter for machines/vehicles", romaji: "-dai" },
  { front: "～はい/ぱい/ばい (～杯)", back: "counter for cups/glasses", romaji: "-hai/-pai/-bai" },
  { front: "～ひき/ぴき/びき (～匹)", back: "counter for small animals", romaji: "-hiki/-piki/-biki" },
  { front: "えん (円)", back: "yen", romaji: "en" },
  { front: "まんえん (万円)", back: "ten thousand yen", romaji: "man'en" },
  { front: "メートル", back: "meter", romaji: "meetoru" },
  { front: "キロメートル", back: "kilometer", romaji: "kiromeetoru" },
  { front: "キロ", back: "kilogram / kilometer", romaji: "kiro" },
  { front: "グラム", back: "gram", romaji: "guramu" },
  { front: "たくさん", back: "many, a lot", romaji: "takusan" },
  { front: "おおい (多い)", back: "many, numerous (adj)", romaji: "ooi" },
  { front: "すこし (少し)", back: "a little, a few", romaji: "sukoshi" },
  { front: "ちょっと", back: "a little (colloquial)", romaji: "chotto" },
  { front: "はんぶん (半分)", back: "half (portion)", romaji: "hanbun" },
  { front: "ぐらい / くらい", back: "about, approximately", romaji: "gurai / kurai" },
  { front: "ばんごう (番号)", back: "number (ID, phone)", romaji: "bangou" },
  { front: "でんわばんごう (電話番号)", back: "telephone number", romaji: "denwabangou" },
  ],
  'time-dates-frequency': [
  { front: "～じ (～時)", back: "o'clock", romaji: "-ji" },
  { front: "～ふん / ぷん (～分)", back: "minute(s)", romaji: "-fun / -pun" },
  { front: "はん (半)", back: "half (hour)", romaji: "han" },
  { front: "～じかん (～時間)", back: "hour(s), time duration", romaji: "-jikan" },
  { front: "あさ (朝)", back: "morning", romaji: "asa" },
  { front: "ひる (昼)", back: "noon, daytime", romaji: "hiru" },
  { front: "ゆうがた (夕方)", back: "evening", romaji: "yuugata" },
  { front: "ばん (晩)", back: "evening, night", romaji: "ban" },
  { front: "よる (夜)", back: "night", romaji: "yoru" },
  { front: "けさ (今朝)", back: "this morning", romaji: "kesa" },
  { front: "こんばん (今晩)", back: "this evening, tonight", romaji: "konban" },
  { front: "きょう (今日)", back: "today", romaji: "kyou" },
  { front: "きのう (昨日)", back: "yesterday", romaji: "kinou" },
  { front: "おととい", back: "day before yesterday", romaji: "ototoi" },
  { front: "あした (明日)", back: "tomorrow", romaji: "ashita" },
  { front: "あさって", back: "day after tomorrow", romaji: "asatte" },
  { front: "こんしゅう (今週)", back: "this week", romaji: "konshuu" },
  { front: "せんしゅう (先週)", back: "last week", romaji: "senshuu" },
  { front: "らいしゅう (来週)", back: "next week", romaji: "raishuu" },
  { front: "こんげつ (今月)", back: "this month", romaji: "kongetsu" },
  { front: "せんげつ (先月)", back: "last month", romaji: "sengetsu" },
  { front: "らいげつ (来月)", back: "next month", romaji: "raigetsu" },
  { front: "ことし (今年)", back: "this year", romaji: "kotoshi" },
  { front: "きょねん (去年)", back: "last year", romaji: "kyonen" },
  { front: "らいねん (来年)", back: "next year", romaji: "rainen" },
  { front: "ひ (日)", back: "day, sun", romaji: "hi" },
  { front: "～にち (～日)", back: "day (counter/name)", romaji: "-nichi" },
  { front: "しゅうかん (週間)", back: "week(s) duration", romaji: "shuukan" },
  { front: "～かかん (～日間)", back: "day(s) duration", romaji: "-kakan" },
  { front: "～かげつ / つき (～ヶ月/月)", back: "month(s) duration", romaji: "-kagetsu / -tsuki" },
  { front: "～ねん (～年)", back: "year", romaji: "-nen" },
  { front: "しゅうまつ (週末)", back: "weekend", romaji: "shuumatsu" },
  { front: "やすみ (休み)", back: "holiday, day off, absence", romaji: "yasumi" },
  { front: "げつようび (月曜日)", back: "Monday", romaji: "getsuyoubi" },
  { front: "かようび (火曜日)", back: "Tuesday", romaji: "kayoubi" },
  { front: "すいようび (水曜日)", back: "Wednesday", romaji: "suiyoubi" },
  { front: "もくようび (木曜日)", back: "Thursday", romaji: "mokuyoubi" },
  { front: "きんようび (金曜日)", back: "Friday", romaji: "kinyoubi" },
  { front: "どようび (土曜日)", back: "Saturday", romaji: "doyoubi" },
  { front: "にちようび (日曜日)", back: "Sunday", romaji: "nichiyoubi" },
  { front: "なんようび (何曜日)", back: "what day of the week?", romaji: "nanyoubi" },
  { front: "ついたち (一日)", back: "1st day", romaji: "tsuitachi" },
  { front: "ふつか (二日)", back: "2nd day / two days", romaji: "futsuka" },
  { front: "みっか (三日)", back: "3rd day / three days", romaji: "mikka" },
  { front: "よっか (四日)", back: "4th day / four days", romaji: "yokka" },
  { front: "いつか (五日)", back: "5th day / five days", romaji: "itsuka" },
  { front: "むいか (六日)", back: "6th day / six days", romaji: "muika" },
  { front: "なのか (七日)", back: "7th day / seven days", romaji: "nanoka" },
  { front: "ようか (八日)", back: "8th day / eight days", romaji: "youka" },
  { front: "ここのか (九日)", back: "9th day / nine days", romaji: "kokonoka" },
  { front: "とおか (十日)", back: "10th day / ten days", romaji: "tooka" },
  { front: "じゅうよっか (十四日)", back: "14th day", romaji: "juuyokka" },
  { front: "はつか (二十日)", back: "20th day", romaji: "hatsuka" },
  { front: "にじゅうよっか (二十四日)", back: "24th day", romaji: "nijuuyokka" },
  { front: "なんにち (何日)", back: "what day / how many days", romaji: "nannichi" },
  { front: "まいにち (毎日)", back: "every day", romaji: "mainichi" },
  { front: "まいあさ (毎朝)", back: "every morning", romaji: "maiasa" },
  { front: "まいばん (毎晩)", back: "every night", romaji: "maiban" },
  { front: "まいしゅう (毎週)", back: "every week", romaji: "maishuu" },
  { front: "まいつき / まいげつ (毎月)", back: "every month", romaji: "maitsuki / maigetsu" },
  { front: "まいとし / まいねん (毎年)", back: "every year", romaji: "maitoshi / mainen" },
  { front: "いつも", back: "always", romaji: "itsumo" },
  { front: "よく", back: "often", romaji: "yoku" },
  { front: "ときどき (時々)", back: "sometimes", romaji: "tokidoki" },
  { front: "あまり", back: "not much/often (+ neg)", romaji: "amari" },
  { front: "ぜんぜん (全然)", back: "not at all (+ neg)", romaji: "zenzen" },
  { front: "たいてい", back: "usually, generally", romaji: "taitei" },
  { front: "いま (今)", back: "now", romaji: "ima" },
  { front: "すぐ", back: "soon, right away", romaji: "sugu" },
  { front: "もうすぐ", back: "soon", romaji: "mousugu" },
  { front: "あとで (後で)", back: "later", romaji: "atode" },
  { front: "さっき", back: "a little while ago", romaji: "sakki" },
  { front: "むかし (昔)", back: "long ago", romaji: "mukashi" },
  { front: "とき (時)", back: "time, when", romaji: "toki" },
  { front: "ごろ", back: "around (time point)", romaji: "goro" },
  { front: "まえ (前)", back: "before, front", romaji: "mae" },
  { front: "あと (後)", back: "after, later", romaji: "ato" },
  { front: "これから", back: "from now on", romaji: "korekara" },
  { front: "こんど (今度)", back: "next time, this time", romaji: "kondo" },
  { front: "さいしょに (最初に)", back: "firstly", romaji: "saisho ni" },
  { front: "つぎに (次に)", back: "next, secondly", romaji: "tsugi ni" },
  { front: "さいごに (最後に)", back: "finally", romaji: "saigo ni" },
  { front: "はやい (早い)", back: "early", romaji: "hayai" },
  { front: "おそい (遅い)", back: "late", romaji: "osoi" },
  { front: "まだ", back: "still, not yet (+ neg)", romaji: "mada" },
  { front: "もう", back: "already, anymore", romaji: "mou" },
  ],
  'location-direction': [
  { front: "うえ (上)", back: "up, above, on top", romaji: "ue" },
  { front: "した (下)", back: "down, below, under", romaji: "shita" },
  { front: "まえ (前)", back: "front, before", romaji: "mae" },
  { front: "うしろ (後ろ)", back: "behind, back", romaji: "ushiro" },
  { front: "みぎ (右)", back: "right (side)", romaji: "migi" },
  { front: "ひだり (左)", back: "left (side)", romaji: "hidari" },
  { front: "なか (中)", back: "inside, middle", romaji: "naka" },
  { front: "そと (外)", back: "outside", romaji: "soto" },
  { front: "となり (隣)", back: "next to, beside (similar items)", romaji: "tonari" },
  { front: "よこ (横)", back: "side, beside (general)", romaji: "yoko" },
  { front: "ちかく (近く)", back: "near, vicinity (noun)", romaji: "chikaku" },
  { front: "そば", back: "nearby, beside", romaji: "soba" },
  { front: "あいだ (間)", back: "between, interval", romaji: "aida" },
  { front: "ここ", back: "here, this place", romaji: "koko" },
  { front: "そこ", back: "there, that place", romaji: "soko" },
  { front: "あそこ", back: "over there", romaji: "asoko" },
  { front: "どこ", back: "where", romaji: "doko" },
  { front: "こちら", back: "this way (polite)", romaji: "kochira" },
  { front: "そちら", back: "that way, there (polite)", romaji: "sochira" },
  { front: "あちら", back: "that way, over there (polite)", romaji: "achira" },
  { front: "どちら", back: "which way, where (polite)", romaji: "dochira" },
  { front: "むこう (向こう)", back: "over there, beyond", romaji: "mukou" },
  { front: "まっすぐ", back: "straight ahead", romaji: "massugu" },
  { front: "かど (角)", back: "corner (street)", romaji: "kado" },
  { front: "いりぐち (入口)", back: "entrance", romaji: "iriguchi" },
  { front: "でぐち (出口)", back: "exit", romaji: "deguchi" },
  { front: "にし (西)", back: "west", romaji: "nishi" },
  { front: "ひがし (東)", back: "east", romaji: "higashi" },
  { front: "みなみ (南)", back: "south", romaji: "minami" },
  { front: "きた (北)", back: "north", romaji: "kita" },
  { front: "ちゅう (中)", back: "in, middle of, during (suffix)", romaji: "chuu" },
  { front: "うら (裏)", back: "back side, reverse side", romaji: "ura" },
  { front: "ところ (所)", back: "place", romaji: "tokoro" },
  ],
  'common-verbs': [
  { front: "います", back: "be, exist (animate)", romaji: "imasu" },
  { front: "あります", back: "be, exist, have (inanimate)", romaji: "arimasu" },
  { front: "いきます (行きます)", back: "go", romaji: "ikimasu" },
  { front: "きます (来ます)", back: "come", romaji: "kimasu" },
  { front: "かえります (帰ります)", back: "return, go back", romaji: "kaerimasu" },
  { front: "あるきます (歩きます)", back: "walk", romaji: "arukimasu" },
  { front: "はしります (走ります)", back: "run", romaji: "hashirimasu" },
  { front: "とびます (飛びます)", back: "fly, jump", romaji: "tobimasu" },
  { front: "のります (乗ります)", back: "ride, get on", romaji: "norimasu" },
  { front: "おります (降ります)", back: "get off", romaji: "orimasu" },
  { front: "でかけます (出かけます)", back: "go out", romaji: "dekakemasu" },
  { front: "でます (出ます)", back: "leave, exit, attend", romaji: "demasu" },
  { front: "はいります (入ります)", back: "enter", romaji: "hairimasu" },
  { front: "まがります (曲がります)", back: "turn (corner)", romaji: "magarimasu" },
  { front: "わたります (渡ります)", back: "cross", romaji: "watarimasu" },
  { front: "とまります (止まります/泊まります)", back: "stop / stay at", romaji: "tomarimasu" },
  { front: "のぼります (登ります)", back: "climb, go up", romaji: "noborimasu" },
  { front: "あがります (上がります)", back: "go up, rise", romaji: "agarimasu" },
  { front: "おきます (起きます)", back: "get up, wake up", romaji: "okimasu" },
  { front: "ねます (寝ます)", back: "sleep, go to bed", romaji: "nemasu" },
  { front: "はたらきます (働きます)", back: "work", romaji: "hatarakimasu" },
  { front: "やすみます (休みます)", back: "rest, take day off", romaji: "yasumimasu" },
  { front: "べんきょうします (勉強します)", back: "study", romaji: "benkyoushimasu" },
  { front: "おわります (終わります)", back: "end, finish", romaji: "owarimasu" },
  { front: "はじまります (始まります)", back: "begin, start (intr.)", romaji: "hajimarimasu" },
  { front: "つくります (作ります)", back: "make, create, cook", romaji: "tsukurimasu" },
  { front: "あらいます (洗います)", back: "wash", romaji: "araimasu" },
  { front: "そうじします (掃除します)", back: "clean", romaji: "soujishimasu" },
  { front: "せんたくします (洗濯します)", back: "do laundry", romaji: "sentakushimasu" },
  { front: "みがきます (磨きます)", back: "polish, brush (teeth)", romaji: "migakimasu" },
  { front: "たべます (食べます)", back: "eat", romaji: "tabemasu" },
  { front: "のみます (飲みます)", back: "drink", romaji: "nomimasu" },
  { front: "いいます (言います)", back: "say, tell", romaji: "iimasu" },
  { front: "はなします (話します)", back: "speak, talk", romaji: "hanashimasu" },
  { front: "ききます (聞きます/訊きます)", back: "listen, hear / ask", romaji: "kikimasu" },
  { front: "よみます (読みます)", back: "read", romaji: "yomimasu" },
  { front: "かきます (書きます)", back: "write, draw", romaji: "kakimasu" },
  { front: "しります (知ります)", back: "know", romaji: "shirimasu" },
  { front: "わかります (分かります)", back: "understand", romaji: "wakarimasu" },
  { front: "おしえます (教えます)", back: "teach, tell, inform", romaji: "oshiemasu" },
  { front: "ならいます (習います)", back: "learn (from someone)", romaji: "naraimasu" },
  { front: "おぼえます (覚えます)", back: "memorize, remember", romaji: "oboemasu" },
  { front: "わすれます (忘れます)", back: "forget", romaji: "wasuremasu" },
  { front: "しつもんします (質問します)", back: "ask a question", romaji: "shitsumon shimasu" },
  { front: "こたえます (答えます)", back: "answer, reply", romaji: "kotaemasu" },
  { front: "よびます (呼びます)", back: "call, invite", romaji: "yobimasu" },
  { front: "でんわします (電話します)", back: "make phone call", romaji: "denwa shimasu" },
  { front: "みます (見ます)", back: "see, watch, look", romaji: "mimasu" },
  { front: "みせます (見せます)", back: "show", romaji: "misemasu" },
  { front: "あいます (会います)", back: "meet", romaji: "aimasu" },
  { front: "つかいます (使います)", back: "use", romaji: "tsukaimasu" },
  { front: "もちます (持ちます)", back: "hold, have, carry", romaji: "mochimasu" },
  { front: "とります (取ります/撮ります)", back: "take, get / take photo", romaji: "torimasu" },
  { front: "おきます (置きます)", back: "put, place", romaji: "okimasu" },
  { front: "いれます (入れます)", back: "put in, insert", romaji: "iremasu" },
  { front: "だします (出します)", back: "take out, submit, send", romaji: "dashimasu" },
  { front: "あけます (開けます)", back: "open (transitive)", romaji: "akemasu" },
  { front: "あきます (開きます)", back: "open (intransitive)", romaji: "akimasu" },
  { front: "しめます (閉めます)", back: "close (transitive)", romaji: "shimemasu" },
  { front: "しまります (閉まります)", back: "close (intransitive)", romaji: "shimarimasu" },
  { front: "つけます", back: "turn on (light, TV)", romaji: "tsukemasu" },
  { front: "けします (消します)", back: "turn off, erase", romaji: "keshimasu" },
  { front: "あげます", back: "give (to others)", romaji: "agemasu" },
  { front: "もらいます", back: "receive", romaji: "moraimasu" },
  { front: "くれます", back: "give (to me/my group)", romaji: "kuremasu" },
  { front: "かします (貸します)", back: "lend", romaji: "kashimasu" },
  { front: "かります (借ります)", back: "borrow", romaji: "karimasu" },
  { front: "かえします (返します)", back: "return (an object)", romaji: "kaeshimasu" },
  { front: "わたします (渡します)", back: "hand over, pass", romaji: "watashimasu" },
  { front: "かいます (買います)", back: "buy", romaji: "kaimasu" },
  { front: "うります (売ります)", back: "sell", romaji: "urimasu" },
  { front: "まちます (待ちます)", back: "wait", romaji: "machimasu" },
  { front: "いそぎます (急ぎます)", back: "hurry", romaji: "isogimasu" },
  { front: "きます (着ます)", back: "wear (upper body)", romaji: "kimasu" },
  { front: "はきます", back: "wear (lower body/feet)", romaji: "hakimasu" },
  { front: "かぶります", back: "wear (on head)", romaji: "kaburimasu" },
  { front: "かけます", back: "wear (glasses)", romaji: "kakemasu" },
  { front: "します", back: "wear (accessories) / do", romaji: "shimasu" },
  { front: "ぬぎます (脱ぎます)", back: "take off (clothes)", romaji: "nugimasu" },
  { front: "あそびます (遊びます)", back: "play, hang out, visit", romaji: "asobimasu" },
  { front: "およぎます (泳ぎます)", back: "swim", romaji: "oyogimasu" },
  { front: "うたいます (歌います)", back: "sing", romaji: "utaimasu" },
  { front: "ひきます (弾きます)", back: "play (string/keyboard)", romaji: "hikimasu" },
  { front: "さんぽします (散歩します)", back: "take a walk", romaji: "sanposhimasu" },
  { front: "りょこうします (旅行します)", back: "travel", romaji: "ryokoushimasu" },
  { front: "れんしゅうします (練習します)", back: "practice", romaji: "renshuushimasu" },
  { front: "すみます (住みます)", back: "live, reside", romaji: "sumimasu" },
  { front: "すわります (座ります)", back: "sit down", romaji: "suwarimasu" },
  { front: "たちます (立ちます)", back: "stand up", romaji: "tachimasu" },
  { front: "つかれます (疲れます)", back: "get tired", romaji: "tsukaremasu" },
  { front: "しにます (死にます)", back: "die", romaji: "shinimasu" },
  { front: "こまります (困ります)", back: "be troubled", romaji: "komarimasu" },
  { front: "ちがいます (違います)", back: "be different, wrong", romaji: "chigaimasu" },
  { front: "まちがえます (間違えます)", back: "make a mistake", romaji: "machigaemasu" },
  { front: "できます", back: "can do, be able to, be completed", romaji: "dekimasu" },
  { front: "すいます (吸います)", back: "smoke, inhale", romaji: "suimasu" },
  { front: "やくそくします (約束します)", back: "promise", romaji: "yakusokushimasu" },
  { front: "ならびます (並びます)", back: "line up (intr.)", romaji: "narabimasu" },
  { front: "ならべます (並べます)", back: "line up (trans.)", romaji: "narabemasu" },
  { front: "ふります (降ります)", back: "fall (rain, snow)", romaji: "furimasu" },
  { front: "コピーします", back: "make a copy", romaji: "kopiishimasu" },
  ],
  'common-adjectives': [
  { front: "おおきい (大きい)", back: "big, large", romaji: "ookii" },
  { front: "ちいさい (小さい)", back: "small, little", romaji: "chiisai" },
  { front: "ながい (長い)", back: "long", romaji: "nagai" },
  { front: "みじかい (短い)", back: "short (length)", romaji: "mijikai" },
  { front: "たかい (高い)", back: "tall, high / expensive", romaji: "takai" },
  { front: "ひくい (低い)", back: "low", romaji: "hikui" },
  { front: "ひろい (広い)", back: "spacious, wide", romaji: "hiroi" },
  { front: "せまい (狭い)", back: "narrow", romaji: "semai" },
  { front: "ふとい (太い)", back: "thick, fat (cylindrical)", romaji: "futoi" },
  { front: "ほそい (細い)", back: "thin, slender", romaji: "hosoi" },
  { front: "あつい (厚い)", back: "thick (flat)", romaji: "atsui" },
  { front: "うすい (薄い)", back: "thin (material), weak (taste)", romaji: "usui" },
  { front: "あたらしい (新しい)", back: "new", romaji: "atarashii" },
  { front: "ふるい (古い)", back: "old (not people)", romaji: "furui" },
  { front: "わかい (若い)", back: "young", romaji: "wakai" },
  { front: "いい / よい (良い)", back: "good", romaji: "ii / yoi" },
  { front: "わるい (悪い)", back: "bad, wrong", romaji: "warui" },
  { front: "ただしい (正しい)", back: "correct", romaji: "tadashii" },
  { front: "むずかしい (難しい)", back: "difficult", romaji: "muzukashii" },
  { front: "やさしい (易しい / 優しい)", back: "easy / kind", romaji: "yasashii" },
  { front: "やすい (安い)", back: "cheap, inexpensive", romaji: "yasui" },
  { front: "おもしろい (面白い)", back: "interesting, funny", romaji: "omoshiroi" },
  { front: "つまらない", back: "boring, trivial", romaji: "tsumaranai" },
  { front: "いそがしい (忙しい)", back: "busy", romaji: "isogashii" },
  { front: "ひま (暇な)", back: "free (time)", romaji: "hima (na)" },
  { front: "きれい (綺麗な)", back: "pretty, clean", romaji: "kirei (na)" },
  { front: "きたない (汚い)", back: "dirty", romaji: "kitanai" },
  { front: "おいしい (美味しい)", back: "delicious, tasty", romaji: "oishii" },
  { front: "まずい", back: "bad tasting", romaji: "mazui" },
  { front: "あまい (甘い)", back: "sweet", romaji: "amai" },
  { front: "からい (辛い)", back: "spicy, hot", romaji: "karai" },
  { front: "しょっぱい (塩っぱい)", back: "salty", romaji: "shoppai" },
  { front: "すっぱい (酸っぱい)", back: "sour", romaji: "suppai" },
  { front: "にがい (苦い)", back: "bitter", romaji: "nigai" },
  { front: "あかい (赤い)", back: "red", romaji: "akai" },
  { front: "あおい (青い)", back: "blue", romaji: "aoi" },
  { front: "くろい (黒い)", back: "black", romaji: "kuroi" },
  { front: "しろい (白い)", back: "white", romaji: "shiroi" },
  { front: "きいろい (黄色い)", back: "yellow", romaji: "kiiroi" },
  { front: "ちゃいろい (茶色い)", back: "brown", romaji: "chairoi" },
  { front: "みどり (緑の)", back: "green", romaji: "midori (no)" },
  { front: "ピンク (の)", back: "pink", romaji: "pinku (no)" },
  { front: "いろ (色)", back: "color (noun)", romaji: "iro" },
  { front: "いろいろ (色々な)", back: "various", romaji: "iroiro (na)" },
  { front: "たのしい (楽しい)", back: "fun, enjoyable", romaji: "tanoshii" },
  { front: "うれしい (嬉しい)", back: "happy, pleased", romaji: "ureshii" },
  { front: "かなしい (悲しい)", back: "sad", romaji: "kanashii" },
  { front: "さびしい (寂しい)", back: "lonely", romaji: "sabishii" },
  { front: "こわい (怖い)", back: "scary, afraid", romaji: "kowai" },
  { front: "げんき (元気な)", back: "healthy, energetic", romaji: "genki (na)" },
  { front: "しんせつ (親切な)", back: "kind", romaji: "shinsetsu (na)" },
  { front: "べんり (便利な)", back: "convenient", romaji: "benri (na)" },
  { front: "ふべん (不便な)", back: "inconvenient", romaji: "fuben (na)" },
  { front: "たいせつ (大切な)", back: "important, precious", romaji: "taisetsu (na)" },
  { front: "だいじょうぶ (大丈夫な)", back: "okay, alright", romaji: "daijoubu (na)" },
  { front: "じょうず (上手な)", back: "skillful, good at", romaji: "jouzu (na)" },
  { front: "へた (下手な)", back: "unskillful, bad at", romaji: "heta (na)" },
  { front: "すき (好きな)", back: "like, fond of", romaji: "suki (na)" },
  { front: "きらい (嫌いな)", back: "dislike, hate", romaji: "kirai (na)" },
  { front: "だいすき (大好きな)", back: "like very much, love", romaji: "daisuki (na)" },
  { front: "ゆうめい (有名な)", back: "famous", romaji: "yuumei (na)" },
  { front: "りっぱ (立派な)", back: "splendid, magnificent", romaji: "rippa (na)" },
  { front: "あかるい (明るい)", back: "bright, light", romaji: "akarui" },
  { front: "くらい (暗い)", back: "dark", romaji: "kurai" },
  { front: "あたたかい (暖かい/温かい)", back: "warm", romaji: "atatakai" },
  { front: "すずしい (涼しい)", back: "cool (weather)", romaji: "suzushii" },
  { front: "あつい (暑い/熱い)", back: "hot (weather/object)", romaji: "atsui" },
  { front: "さむい (寒い)", back: "cold (weather)", romaji: "samui" },
  { front: "つめたい (冷たい)", back: "cold (to touch)", romaji: "tsumetai" },
  { front: "ぬるい", back: "lukewarm", romaji: "nurui" },
  { front: "しずか (静かな)", back: "quiet", romaji: "shizuka (na)" },
  { front: "にぎやか (賑やかな)", back: "lively, bustling", romaji: "nigiyaka (na)" },
  { front: "うるさい", back: "noisy, annoying", romaji: "urusai" },
  { front: "あぶない (危ない)", back: "dangerous", romaji: "abunai" },
  { front: "はやい (速い/早い)", back: "fast / early", romaji: "hayai" },
  { front: "おそい (遅い)", back: "slow / late", romaji: "osoi" },
  { front: "ちかい (近い)", back: "near, close", romaji: "chikai" },
  { front: "とおい (遠い)", back: "far", romaji: "tooi" },
  { front: "つよい (強い)", back: "strong", romaji: "tsuyoi" },
  { front: "よわい (弱い)", back: "weak", romaji: "yowai" },
  { front: "おもい (重い)", back: "heavy", romaji: "omoi" },
  { front: "かるい (軽い)", back: "light (weight)", romaji: "karui" },
  { front: "まるい (丸い)", back: "round", romaji: "marui" },
  { front: "ほしい (欲しい)", back: "want (object)", romaji: "hoshii" },
  ],
  'food-drink': [
  { front: "たべもの (食べ物)", back: "food", romaji: "tabemono" },
  { front: "のみもの (飲み物)", back: "drink, beverage", romaji: "nomimono" },
  { front: "ごはん (ご飯)", back: "cooked rice / meal", romaji: "gohan" },
  { front: "あさごはん (朝ご飯)", back: "breakfast", romaji: "asagohan" },
  { front: "ひるごはん (昼ご飯)", back: "lunch", romaji: "hirugohan" },
  { front: "ばんごはん (晩ご飯)", back: "dinner", romaji: "bangohan" },
  { front: "おべんとう (お弁当)", back: "lunch box", romaji: "obentou" },
  { front: "りょうり (料理)", back: "cooking, cuisine", romaji: "ryouri" },
  { front: "みず (水)", back: "water", romaji: "mizu" },
  { front: "おゆ (お湯)", back: "hot water", romaji: "oyu" },
  { front: "おちゃ (お茶)", back: "tea (green)", romaji: "ocha" },
  { front: "こうちゃ (紅茶)", back: "black tea", romaji: "koucha" },
  { front: "コーヒー", back: "coffee", romaji: "koohii" },
  { front: "ぎゅうにゅう / ミルク (牛乳)", back: "milk", romaji: "gyuunyuu / miruku" },
  { front: "ジュース", back: "juice", romaji: "juusu" },
  { front: "ビール", back: "beer", romaji: "biiru" },
  { front: "ワイン", back: "wine", romaji: "wain" },
  { front: "おさけ (お酒)", back: "alcohol, sake", romaji: "osake" },
  { front: "パン", back: "bread", romaji: "pan" },
  { front: "めん (麺)", back: "noodles", romaji: "men" },
  { front: "にく (肉)", back: "meat", romaji: "niku" },
  { front: "とりにく (鶏肉)", back: "chicken meat", romaji: "toriniku" },
  { front: "ぶたにく (豚肉)", back: "pork", romaji: "butaniku" },
  { front: "ぎゅうにく (牛肉)", back: "beef", romaji: "gyuuniku" },
  { front: "さかな (魚)", back: "fish", romaji: "sakana" },
  { front: "たまご (卵)", back: "egg", romaji: "tamago" },
  { front: "とうふ (豆腐)", back: "tofu", romaji: "tofu" },
  { front: "やさい (野菜)", back: "vegetable", romaji: "yasai" },
  { front: "くだもの (果物)", back: "fruit", romaji: "kudamono" },
  { front: "りんご", back: "apple", romaji: "ringo" },
  { front: "みかん", back: "mandarin orange", romaji: "mikan" },
  { front: "バナナ", back: "banana", romaji: "banana" },
  { front: "おかし (お菓子)", back: "sweets, snacks", romaji: "okashi" },
  { front: "ケーキ", back: "cake", romaji: "keeki" },
  { front: "チョコレート", back: "chocolate", romaji: "chokoreeto" },
  { front: "アイスクリーム", back: "ice cream", romaji: "aisukuriimu" },
  { front: "クリーム", back: "cream", romaji: "kuriimu" },
  { front: "さとう (砂糖)", back: "sugar", romaji: "satou" },
  { front: "しお (塩)", back: "salt", romaji: "shio" },
  { front: "こしょう (胡椒)", back: "pepper (spice)", romaji: "koshou" },
  { front: "しょうゆ (醤油)", back: "soy sauce", romaji: "shouyu" },
  { front: "みそ (味噌)", back: "miso", romaji: "miso" },
  { front: "はし (箸)", back: "chopsticks", romaji: "hashi" },
  { front: "ちゃわん (茶碗)", back: "rice bowl", romaji: "chawan" },
  { front: "おさら (お皿)", back: "plate, dish", romaji: "osara" },
  { front: "コップ", back: "glass, cup (glass)", romaji: "koppu" },
  { front: "カップ", back: "cup (mug-like)", romaji: "kappu" },
  { front: "スプーン", back: "spoon", romaji: "supuun" },
  { front: "フォーク", back: "fork", romaji: "fooku" },
  { front: "ナイフ", back: "knife", romaji: "naifu" },
  ],
  'everyday-objects': [
  { front: "ほん (本)", back: "book", romaji: "hon" },
  { front: "ノート", back: "notebook", romaji: "nooto" },
  { front: "じしょ (辞書)", back: "dictionary", romaji: "jisho" },
  { front: "しんぶん (新聞)", back: "newspaper", romaji: "shinbun" },
  { front: "ざっし (雑誌)", back: "magazine", romaji: "zasshi" },
  { front: "かみ (紙)", back: "paper", romaji: "kami" },
  { front: "てがみ (手紙)", back: "letter", romaji: "tegami" },
  { front: "はがき (葉書)", back: "postcard", romaji: "hagaki" },
  { front: "ふうとう (封筒)", back: "envelope", romaji: "fuutou" },
  { front: "きって (切手)", back: "postage stamp", romaji: "kitte" },
  { front: "えんぴつ (鉛筆)", back: "pencil", romaji: "enpitsu" },
  { front: "ペン", back: "pen", romaji: "pen" },
  { front: "ボールペン", back: "ballpoint pen", romaji: "boorupen" },
  { front: "まんねんひつ (万年筆)", back: "fountain pen", romaji: "mannenhitsu" },
  { front: "けしゴム (消しゴム)", back: "eraser", romaji: "keshigomu" },
  { front: "かばん", back: "bag, briefcase", romaji: "kaban" },
  { front: "さいふ (財布)", back: "wallet, purse", romaji: "saifu" },
  { front: "はこ (箱)", back: "box", romaji: "hako" },
  { front: "ふくろ (袋)", back: "bag, sack", romaji: "fukuro" },
  { front: "ポケット", back: "pocket", romaji: "poketto" },
  { front: "かさ (傘)", back: "umbrella", romaji: "kasa" },
  { front: "かぎ (鍵)", back: "key", romaji: "kagi" },
  { front: "とけい (時計)", back: "watch, clock", romaji: "tokei" },
  { front: "めがね (眼鏡)", back: "glasses", romaji: "megane" },
  { front: "くすり (薬)", back: "medicine", romaji: "kusuri" },
  { front: "おかね (お金)", back: "money", romaji: "okane" },
  { front: "きっぷ (切符)", back: "ticket", romaji: "kippu" },
  { front: "しゃしん (写真)", back: "photograph", romaji: "shashin" },
  { front: "ちず (地図)", back: "map", romaji: "chizu" },
  { front: "カレンダー", back: "calendar", romaji: "karendaa" },
  { front: "マッチ", back: "match (fire)", romaji: "macchi" },
  { front: "たばこ", back: "cigarette, tobacco", romaji: "tabako" },
  { front: "はんこ / いんかん (判子/印鑑)", back: "seal, stamp", romaji: "hanko / inkan" },
  { front: "にもつ (荷物)", back: "luggage, baggage", romaji: "nimotsu" },
  { front: "もの (物)", back: "thing (tangible)", romaji: "mono" },
  { front: "こと (事)", back: "thing (intangible)", romaji: "koto" },
  { front: "じかん (時間)", back: "time", romaji: "jikan" },
  { front: "しごと (仕事)", back: "work, job", romaji: "shigoto" },
  { front: "やくそく (約束)", back: "promise, appointment", romaji: "yakusoku" },
  { front: "はなし (話)", back: "story, talk", romaji: "hanashi" },
  ],
  'home-living': [
  { front: "いえ / うち (家)", back: "house, home", romaji: "ie / uchi" },
  { front: "アパート", back: "apartment (older/smaller)", romaji: "apaato" },
  { front: "マンション", back: "condo, apartment (newer/larger)", romaji: "manshon" },
  { front: "へや (部屋)", back: "room", romaji: "heya" },
  { front: "げんかん (玄関)", back: "entranceway", romaji: "genkan" },
  { front: "だいどころ (台所)", back: "kitchen", romaji: "daidokoro" },
  { front: "しょくどう (食堂)", back: "dining room, cafeteria", romaji: "shokudou" },
  { front: "いま (居間)", back: "living room", romaji: "ima" },
  { front: "しんしつ (寝室)", back: "bedroom", romaji: "shinshitsu" },
  { front: "おふろ / ふろば (お風呂/風呂場)", back: "bath / bathroom", romaji: "ofuro / furoba" },
  { front: "おてあらい / トイレ (お手洗い)", back: "toilet, restroom", romaji: "otearai / toire" },
  { front: "にわ (庭)", back: "garden, yard", romaji: "niwa" },
  { front: "かいだん (階段)", back: "stairs", romaji: "kaidan" },
  { front: "まど (窓)", back: "window", romaji: "mado" },
  { front: "ドア", back: "door", romaji: "doa" },
  { front: "つくえ (机)", back: "desk", romaji: "tsukue" },
  { front: "いす (椅子)", back: "chair", romaji: "isu" },
  { front: "テーブル", back: "table", romaji: "teeburu" },
  { front: "ベッド", back: "bed", romaji: "beddo" },
  { front: "ふとん (布団)", back: "Japanese bedding", romaji: "futon" },
  { front: "ほんだな (本棚)", back: "bookshelf", romaji: "hondana" },
  { front: "たんす (箪笥)", back: "chest of drawers", romaji: "tansu" },
  { front: "でんき (電気)", back: "electricity, light", romaji: "denki" },
  { front: "エアコン", back: "air conditioner", romaji: "eakon" },
  { front: "ストーブ / ヒーター", back: "heater, stove", romaji: "sutoobu / hiitaa" },
  { front: "れいぞうこ (冷蔵庫)", back: "refrigerator", romaji: "reizouko" },
  { front: "せんたくき (洗濯機)", back: "washing machine", romaji: "sentakuki" },
  { front: "そうじき (掃除機)", back: "vacuum cleaner", romaji: "soujiki" },
  { front: "テレビ", back: "television, TV", romaji: "terebi" },
  { front: "ラジオ", back: "radio", romaji: "rajio" },
  { front: "パソコン", back: "personal computer", romaji: "pasokon" },
  { front: "でんわ (電話)", back: "telephone", romaji: "denwa" },
  { front: "せっけん (石鹸)", back: "soap", romaji: "sekken" },
  { front: "シャンプー", back: "shampoo", romaji: "shampuu" },
  { front: "はブラシ (歯ブラシ)", back: "toothbrush", romaji: "haburashi" },
  { front: "タオル", back: "towel", romaji: "taoru" },
  { front: "ティッシュペーパー", back: "tissue paper", romaji: "tisshupeepaa" },
  { front: "トイレットペーパー", back: "toilet paper", romaji: "toirettopepaa" },
  ],
  'places-buildings-public': [
  { front: "まち (町/街)", back: "town, city", romaji: "machi" },
  { front: "むら (村)", back: "village", romaji: "mura" },
  { front: "くに (国)", back: "country, nation", romaji: "kuni" },
  { front: "がいこく (外国)", back: "foreign country", romaji: "gaikoku" },
  { front: "にほん (日本)", back: "Japan", romaji: "nihon" },
  { front: "かいしゃ (会社)", back: "company, office", romaji: "kaisha" },
  { front: "がっこう (学校)", back: "school", romaji: "gakkou" },
  { front: "だいがく (大学)", back: "university", romaji: "daigaku" },
  { front: "びょういん (病院)", back: "hospital", romaji: "byouin" },
  { front: "ぎんこう (銀行)", back: "bank", romaji: "ginkou" },
  { front: "ゆうびんきょく (郵便局)", back: "post office", romaji: "yuubinkyoku" },
  { front: "としょかん (図書館)", back: "library", romaji: "toshokan" },
  { front: "びじゅつかん (美術館)", back: "art museum", romaji: "bijutsukan" },
  { front: "えき (駅)", back: "station", romaji: "eki" },
  { front: "くうこう (空港)", back: "airport", romaji: "kuukou" },
  { front: "ホテル", back: "hotel", romaji: "hoteru" },
  { front: "みせ (店)", back: "store, shop", romaji: "mise" },
  { front: "レストラン", back: "restaurant", romaji: "resutoran" },
  { front: "きっさてん (喫茶店)", back: "coffee shop, cafe", romaji: "kissaten" },
  { front: "スーパー", back: "supermarket", romaji: "suupaa" },
  { front: "デパート", back: "department store", romaji: "depaato" },
  { front: "コンビニ", back: "convenience store", romaji: "konbini" },
  { front: "えいがかん (映画館)", back: "movie theater", romaji: "eigakan" },
  { front: "こうえん (公園)", back: "park", romaji: "kouen" },
  { front: "プール", back: "swimming pool", romaji: "puuru" },
  { front: "たいしかん (大使館)", back: "embassy", romaji: "taishikan" },
  { front: "けいさつしょ / こうばん (警察署/交番)", back: "police station / police box", romaji: "keisatsusho / kouban" },
  { front: "たてもの (建物)", back: "building", romaji: "tatemono" },
  { front: "みち (道)", back: "road, street", romaji: "michi" },
  { front: "はし (橋)", back: "bridge", romaji: "hashi" },
  { front: "いけ (池)", back: "pond", romaji: "ike" },
  { front: "エレベーター", back: "elevator", romaji: "erebeetaa" },
  { front: "エスカレーター", back: "escalator", romaji: "esukareetaa" },
  ],
  'transportation': [
  { front: "くるま / じどうしゃ (車/自動車)", back: "car, automobile", romaji: "kuruma / jidousha" },
  { front: "バス", back: "bus", romaji: "basu" },
  { front: "タクシー", back: "taxi", romaji: "takushii" },
  { front: "じてんしゃ (自転車)", back: "bicycle", romaji: "jitensha" },
  { front: "でんしゃ (電車)", back: "train (electric)", romaji: "densha" },
  { front: "ちかてつ (地下鉄)", back: "subway", romaji: "chikatetsu" },
  { front: "しんかんせん (新幹線)", back: "bullet train", romaji: "shinkansen" },
  { front: "ひこうき (飛行機)", back: "airplane", romaji: "hikouki" },
  { front: "ふね (船)", back: "boat, ship", romaji: "fune" },
  { front: "バイク", back: "motorcycle", romaji: "baiku" },
  { front: "えき (駅)", back: "station", romaji: "eki" },
  { front: "くうこう (空港)", back: "airport", romaji: "kuukou" },
  { front: "バスてい (バス停)", back: "bus stop", romaji: "basutei" },
  { front: "のりば (乗り場)", back: "boarding place", romaji: "noriba" },
  { front: "きっぷ (切符)", back: "ticket", romaji: "kippu" },
  { front: "のります (乗ります)", back: "ride, get on", romaji: "norimasu" },
  { front: "おります (降ります)", back: "get off", romaji: "orimasu" },
  { front: "のりかえます (乗り換えます)", back: "change (transport)", romaji: "norikaemasu" },
  { front: "うんてんします (運転します)", back: "drive", romaji: "untenshimasu" },
  ],
  'school-study': [
  { front: "がっこう (学校)", back: "school", romaji: "gakkou" },
  { front: "だいがく (大学)", back: "university", romaji: "daigaku" },
  { front: "がくせい (学生)", back: "student", romaji: "gakusei" },
  { front: "せんせい (先生)", back: "teacher", romaji: "sensei" },
  { front: "クラス", back: "class", romaji: "kurasu" },
  { front: "じゅぎょう (授業)", back: "class, lesson", romaji: "jugyou" },
  { front: "べんきょうします (勉強します)", back: "study", romaji: "benkyoushimasu" },
  { front: "ならいます (習います)", back: "learn (from someone)", romaji: "naraimasu" },
  { front: "おしえます (教えます)", back: "teach, inform", romaji: "oshiemasu" },
  { front: "おぼえます (覚えます)", back: "memorize, remember", romaji: "oboemasu" },
  { front: "わかります (分かります)", back: "understand", romaji: "wakarimasu" },
  { front: "しつもん (質問)", back: "question (noun)", romaji: "shitsumon" },
  { front: "こたえ (答え)", back: "answer (noun)", romaji: "kotae" },
  { front: "れい (例)", back: "example", romaji: "rei" },
  { front: "きょうかしょ (教科書)", back: "textbook", romaji: "kyoukasho" },
  { front: "じしょ (辞書)", back: "dictionary", romaji: "jisho" },
  { front: "ノート", back: "notebook", romaji: "nooto" },
  { front: "えんぴつ (鉛筆)", back: "pencil", romaji: "enpitsu" },
  { front: "ペン", back: "pen", romaji: "pen" },
  { front: "けしゴム (消しゴム)", back: "eraser", romaji: "keshigomu" },
  { front: "つくえ (机)", back: "desk", romaji: "tsukue" },
  { front: "いす (椅子)", back: "chair", romaji: "isu" },
  { front: "しゅくだい (宿題)", back: "homework", romaji: "shukudai" },
  { front: "しけん (試験)", back: "exam, test", romaji: "shiken" },
  { front: "れんしゅう (練習)", back: "practice (noun)", romaji: "renshuu" },
  { front: "れんしゅうします (練習します)", back: "practice (verb)", romaji: "renshuushimasu" },
  { front: "さくぶん (作文)", back: "composition, essay", romaji: "sakubun" },
  { front: "ページ", back: "page", romaji: "peeji" },
  ],
  'hobbies-art-media': [
  { front: "しゅみ (趣味)", back: "hobby", romaji: "shumi" },
  { front: "え (絵)", back: "drawing, picture", romaji: "e" },
  { front: "おんがく (音楽)", back: "music", romaji: "ongaku" },
  { front: "うた (歌)", back: "song", romaji: "uta" },
  { front: "うたいます (歌います)", back: "sing", romaji: "utaimasu" },
  { front: "ギター", back: "guitar", romaji: "gitaa" },
  { front: "ピアノ", back: "piano", romaji: "piano" },
  { front: "ひきます (弾きます)", back: "play (string/keyboard)", romaji: "hikimasu" },
  { front: "えいが (映画)", back: "movie, film", romaji: "eiga" },
  { front: "テレビ", back: "television, TV", romaji: "terebi" },
  { front: "ラジオ", back: "radio", romaji: "rajio" },
  { front: "しんぶん (新聞)", back: "newspaper", romaji: "shinbun" },
  { front: "ざっし (雑誌)", back: "magazine", romaji: "zasshi" },
  { front: "ほん (本)", back: "book", romaji: "hon" },
  { front: "ニュース", back: "news", romaji: "nyuusu" },
  { front: "カメラ", back: "camera", romaji: "kamera" },
  { front: "しゃしん (写真)", back: "photograph", romaji: "shashin" },
  { front: "とります (撮ります)", back: "take (a photo)", romaji: "torimasu" },
  { front: "フィルム", back: "film (camera)", romaji: "firumu" },
  { front: "レコード", back: "record (vinyl)", romaji: "rekoodo" },
  { front: "テープ", back: "tape (cassette)", romaji: "teepu" },
  { front: "テープレコーダー", back: "tape recorder", romaji: "teepurekooda" },
  { front: "スポーツ", back: "sports", romaji: "supootsu" },
  { front: "します", back: "play (sports)", romaji: "shimasu" },
  { front: "サッカー", back: "soccer, football", romaji: "sakkaa" },
  { front: "テニス", back: "tennis", romaji: "tenisu" },
  { front: "やきゅう (野球)", back: "baseball", romaji: "yakyuu" },
  { front: "およぎます (泳ぎます)", back: "swim", romaji: "oyogimasu" },
  { front: "プール", back: "swimming pool", romaji: "puuru" },
  { front: "さんぽします (散歩します)", back: "take a walk", romaji: "sanposhimasu" },
  { front: "やまのぼり (山登り)", back: "mountain climbing", romaji: "yamanobori" },
  { front: "りょこう (旅行)", back: "travel, trip (noun)", romaji: "ryokou" },
  { front: "りょこうします (旅行します)", back: "travel (verb)", romaji: "ryokoushimasu" },
  { front: "あそびます (遊びます)", back: "play, have fun", romaji: "asobimasu" },
  { front: "パーティー", back: "party", romaji: "paatii" },
  ],
  'clothing-accessories': [
  { front: "ふく (服)", back: "clothes", romaji: "fuku" },
  { front: "ようふく (洋服)", back: "western clothes", romaji: "youfuku" },
  { front: "わふく / きもの (和服/着物)", back: "Japanese clothes / kimono", romaji: "wafuku / kimono" },
  { front: "シャツ", back: "shirt", romaji: "shatsu" },
  { front: "ワイシャツ", back: "business shirt", romaji: "waishatsu" },
  { front: "ブラウス", back: "blouse", romaji: "burausu" },
  { front: "セーター", back: "sweater", romaji: "seetaa" },
  { front: "コート", back: "coat", romaji: "kooto" },
  { front: "うわぎ (上着)", back: "jacket, outerwear", romaji: "uwagi" },
  { front: "したぎ (下着)", back: "underwear", romaji: "shitagi" },
  { front: "ズボン / パンツ", back: "pants, trousers", romaji: "zubon / pantsu" },
  { front: "スカート", back: "skirt", romaji: "sukaato" },
  { front: "ドレス", back: "dress", romaji: "doresu" },
  { front: "くつ (靴)", back: "shoes", romaji: "kutsu" },
  { front: "くつした (靴下)", back: "socks", romaji: "kutsushita" },
  { front: "ぼうし (帽子)", back: "hat, cap", romaji: "boushi" },
  { front: "めがね (眼鏡)", back: "glasses", romaji: "megane" },
  { front: "ネクタイ", back: "necktie", romaji: "nekutai" },
  { front: "てぶくろ (手袋)", back: "gloves", romaji: "tebukuro" },
  { front: "マフラー", back: "scarf (winter)", romaji: "mafuraa" },
  { front: "ゆびわ (指輪)", back: "ring (finger)", romaji: "yubiwa" },
  { front: "とけい / うでどけい (時計/腕時計)", back: "clock / wristwatch", romaji: "tokei / udedokei" },
  { front: "ハンカチ", back: "handkerchief", romaji: "hankachi" },
  { front: "かばん", back: "bag", romaji: "kaban" },
  { front: "ポケット", back: "pocket", romaji: "poketto" },
  { front: "きます (着ます)", back: "wear (upper body)", romaji: "kimasu" },
  { front: "はきます", back: "wear (lower body/feet)", romaji: "hakimasu" },
  { front: "かぶります", back: "wear (on head)", romaji: "kaburimasu" },
  { front: "かけます", back: "wear (glasses)", romaji: "kakemasu" },
  { front: "します", back: "wear (accessories)", romaji: "shimasu" },
  { front: "ぬぎます (脱ぎます)", back: "take off (clothes)", romaji: "nugimasu" },
  ],
  'body-health': [
  { front: "からだ (体)", back: "body", romaji: "karada" },
  { front: "あたま (頭)", back: "head", romaji: "atama" },
  { front: "かみ (髪)", back: "hair", romaji: "kami" },
  { front: "かお (顔)", back: "face", romaji: "kao" },
  { front: "め (目)", back: "eye", romaji: "me" },
  { front: "みみ (耳)", back: "ear", romaji: "mimi" },
  { front: "はな (鼻)", back: "nose", romaji: "hana" },
  { front: "くち (口)", back: "mouth", romaji: "kuchi" },
  { front: "は (歯)", back: "tooth", romaji: "ha" },
  { front: "くび (首)", back: "neck", romaji: "kubi" },
  { front: "かた (肩)", back: "shoulder", romaji: "kata" },
  { front: "うで (腕)", back: "arm", romaji: "ude" },
  { front: "て (手)", back: "hand", romaji: "te" },
  { front: "ゆび (指)", back: "finger, toe", romaji: "yubi" },
  { front: "むね (胸)", back: "chest", romaji: "mune" },
  { front: "おなか (お腹)", back: "stomach, abdomen", romaji: "onaka" },
  { front: "せなか (背中)", back: "back (body)", romaji: "senaka" },
  { front: "こし (腰)", back: "lower back, waist", romaji: "koshi" },
  { front: "あし (足)", back: "foot, leg", romaji: "ashi" },
  { front: "げんき (元気)", back: "healthy, energetic", romaji: "genki" },
  { front: "びょうき (病気)", back: "illness, sickness", romaji: "byouki" },
  { front: "いたい (痛い)", back: "painful, sore (adj)", romaji: "itai" },
  { front: "いたみ (痛み)", back: "pain (noun)", romaji: "itami" },
  { front: "かぜ (風邪)", back: "a cold (illness)", romaji: "kaze" },
  { front: "ねつ (熱)", back: "fever", romaji: "netsu" },
  { front: "けが", back: "injury", romaji: "kega" },
  { front: "くすり (薬)", back: "medicine", romaji: "kusuri" },
  { front: "びょういん (病院)", back: "hospital", romaji: "byouin" },
  { front: "いしゃ (医者)", back: "doctor", romaji: "isha" },
  { front: "かんごし (看護師)", back: "nurse", romaji: "kangoshi" },
  { front: "しにます (死にます)", back: "die", romaji: "shinimasu" },
  { front: "つかれます (疲れます)", back: "get tired", romaji: "tsukaremasu" },
  { front: "シャワー", back: "shower", romaji: "shawā" },
  { front: "あびます (浴びます)", back: "take (shower), bathe", romaji: "abimasu" },
  { front: "はいります (入ります)", back: "take (a bath)", romaji: "hairimasu" },
  { front: "せい (背)", back: "height, stature (noun)", romaji: "sei" },
  { front: "こえ (声)", back: "voice", romaji: "koe" },
  ],
  'nature-weather': [
  { front: "やま (山)", back: "mountain", romaji: "yama" },
  { front: "かわ (川)", back: "river", romaji: "kawa" },
  { front: "うみ (海)", back: "sea, ocean", romaji: "umi" },
  { front: "そら (空)", back: "sky", romaji: "sora" },
  { front: "たいよう / ひ (太陽/日)", back: "sun", romaji: "taiyou / hi" },
  { front: "つき (月)", back: "moon", romaji: "tsuki" },
  { front: "ほし (星)", back: "star", romaji: "hoshi" },
  { front: "き (木)", back: "tree, wood", romaji: "ki" },
  { front: "はな (花)", back: "flower", romaji: "hana" },
  { front: "いけ (池)", back: "pond", romaji: "ike" },
  { front: "いし (石)", back: "stone, rock", romaji: "ishi" },
  { front: "どうぶつ (動物)", back: "animal", romaji: "doubutsu" },
  { front: "いぬ (犬)", back: "dog", romaji: "inu" },
  { front: "ねこ (猫)", back: "cat", romaji: "neko" },
  { front: "とり (鳥)", back: "bird", romaji: "tori" },
  { front: "さかな (魚)", back: "fish", romaji: "sakana" },
  { front: "むし (虫)", back: "insect", romaji: "mushi" },
  { front: "てんき (天気)", back: "weather", romaji: "tenki" },
  { front: "はれ (晴れ)", back: "clear weather, sunny", romaji: "hare" },
  { front: "くもり (曇り)", back: "cloudy weather", romaji: "kumori" },
  { front: "あめ (雨)", back: "rain", romaji: "ame" },
  { front: "ゆき (雪)", back: "snow", romaji: "yuki" },
  { front: "かぜ (風)", back: "wind", romaji: "kaze" },
  { front: "くも (雲)", back: "cloud", romaji: "kumo" },
  { front: "たいふう (台風)", back: "typhoon", romaji: "taifuu" },
  { front: "ふります (降ります)", back: "fall (rain, snow)", romaji: "furimasu" },
  { front: "あたたかい (暖かい)", back: "warm (weather)", romaji: "atatakai" },
  { front: "すずしい (涼しい)", back: "cool (weather)", romaji: "suzushii" },
  { front: "あつい (暑い)", back: "hot (weather)", romaji: "atsui" },
  { front: "さむい (寒い)", back: "cold (weather)", romaji: "samui" },
  { front: "きせつ (季節)", back: "season", romaji: "kisetsu" },
  { front: "はる (春)", back: "spring", romaji: "haru" },
  { front: "なつ (夏)", back: "summer", romaji: "natsu" },
  { front: "あき (秋)", back: "autumn, fall", romaji: "aki" },
  { front: "ふゆ (冬)", back: "winter", romaji: "fuyu" },
  ],
  'language-communication': [
  { front: "ことば (言葉)", back: "word, language", romaji: "kotoba" },
  { front: "～ご (～語)", back: "language suffix", romaji: "-go" },
  { front: "にほんご (日本語)", back: "Japanese language", romaji: "nihongo" },
  { front: "えいご (英語)", back: "English language", romaji: "eigo" },
  { front: "かんじ (漢字)", back: "kanji", romaji: "kanji" },
  { front: "ひらがな", back: "hiragana", romaji: "hiragana" },
  { front: "カタカナ", back: "katakana", romaji: "katakana" },
  { front: "ローマじ", back: "romaji", romaji: "roomaji" },
  { front: "ほんやく (翻訳)", back: "translation", romaji: "honyaku" },
  { front: "いみ (意味)", back: "meaning", romaji: "imi" },
  { front: "でんわ (電話)", back: "telephone", romaji: "denwa" },
  { front: "でんわばんごう (電話番号)", back: "telephone number", romaji: "denwabangou" },
  { front: "でんわします (電話します)", back: "make phone call", romaji: "denwa shimasu" },
  { front: "てがみ (手紙)", back: "letter", romaji: "tegami" },
  { front: "はがき (葉書)", back: "postcard", romaji: "hagaki" },
  { front: "ふうとう (封筒)", back: "envelope", romaji: "fuutou" },
  { front: "きって (切手)", back: "postage stamp", romaji: "kitte" },
  { front: "だします (出します)", back: "send (letter)", romaji: "dashimasu" },
  { front: "メール", back: "email", romaji: "meeru" },
  { front: "パソコン", back: "PC", romaji: "pasokon" },
  { front: "スマホ", back: "smartphone", romaji: "sumaho" },
  { front: "インターネット", back: "internet", romaji: "intaanetto" },
  { front: "コピー", back: "copy", romaji: "kopii" },
  { front: "コピーします", back: "make a copy", romaji: "kopiishimasu" },
  { front: "ファックス", back: "fax", romaji: "fakkusu" },
  { front: "はなします (話します)", back: "speak, talk", romaji: "hanashimasu" },
  { front: "ききます (聞きます/訊きます)", back: "listen / ask", romaji: "kikimasu" },
  { front: "いいます (言います)", back: "say, tell", romaji: "iimasu" },
  { front: "はなし (話)", back: "story, talk", romaji: "hanashi" },
  { front: "しつもん (質問)", back: "question (noun)", romaji: "shitsumon" },
  { front: "こたえ (答え)", back: "answer (noun)", romaji: "kotae" },
  ],
  'other-useful-words': [
  { front: "いっしょに (一緒に)", back: "together", romaji: "isshoni" },
  { front: "ゆっくり", back: "slowly, leisurely", romaji: "yukkuri" },
  { front: "まっすぐ", back: "straight ahead", romaji: "massugu" },
  { front: "たいへん (大変)", back: "very / terrible, hard", romaji: "taihen" },
  { front: "すこし (少し)", back: "a little, a few", romaji: "sukoshi" },
  { front: "ちょっと", back: "a little (colloquial)", romaji: "chotto" },
  { front: "もっと", back: "more", romaji: "motto" },
  { front: "いちばん (一番)", back: "the most, number one", romaji: "ichiban" },
  { front: "よく", back: "well / often", romaji: "yoku" },
  { front: "たぶん (多分)", back: "probably, perhaps", romaji: "tabun" },
  { front: "ほんとうに (本当に)", back: "really, truly", romaji: "hontou ni" },
  { front: "だんだん", back: "gradually", romaji: "dandan" },
  { front: "そして", back: "and (connects sentences)", romaji: "soshite" },
  { front: "それから", back: "and then, after that", romaji: "sorekara" },
  { front: "でも", back: "but, however", romaji: "demo" },
  { front: "ですから / だから", back: "therefore, so", romaji: "desukara / dakara" },
  { front: "じゃあ / それでは", back: "well then, in that case", romaji: "jaa / sore dewa" },
  { front: "ほか (の) (他の)", back: "other, besides", romaji: "hoka (no)" },
  { front: "つぎ (の) (次の)", back: "next", romaji: "tsugi (no)" },
  { front: "はじめ (に) (始めに)", back: "beginning / at the beginning", romaji: "hajime (ni)" },
  { front: "おわり (終わり)", back: "the end", romaji: "owari" },
  { front: "くみ (組)", back: "group, team, set, class", romaji: "kumi" },
  { front: "どうして", back: "why?", romaji: "doushite" },
  { front: "なぜ (何故)", back: "why? (formal)", romaji: "naze" },
  { front: "どうやって", back: "how?", romaji: "douyatte" },
  { front: "ほんとう (本当)", back: "truth, reality (noun)", romaji: "hontou" },
  { front: "なんか", back: "something like... (colloquial)", romaji: "nanka" },
  ] 

};

// This will also be populated later
export const flashcardCategories: { value: string; label: string }[] = []; 